# Generated by Django 3.2.11 on 2022-02-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='UPLOAD DATE'),
        ),
    ]
